import { readManifest } from './manifest';
import { getE2EHarness } from './harness';
import { getScopedId } from './config';

const TAGGED_COLLECTIONS = [
  'orders',
  'repairs',
  'inventory_logs',
  'inventory_lots',
  'customer_ledger',
  'customer_transactions',
  'operation_requests',
  'cashier_shifts',
  'cashier_shift_movements',
  'commissions',
];

type CleanupProgress = (step: string) => void | Promise<void>;

async function deleteTaggedDocuments(runId: string, onProgress?: CleanupProgress) {
  const { db } = getE2EHarness();
  for (const collection of TAGGED_COLLECTIONS) {
    await onProgress?.(`tagged-${collection}`);
    const snapshot = await db.collection(collection).where('e2eRunId', '==', runId).get();
    const batch = db.batch();
    snapshot.docs.forEach(document => batch.delete(document.ref));
    if (!snapshot.empty) await batch.commit();
  }
}

async function clearAuthEmulatorUsers(): Promise<void> {
  const authHost = process.env.FIREBASE_AUTH_EMULATOR_HOST;
  if (!authHost) throw new Error('FIREBASE_AUTH_EMULATOR_HOST is required for E2E cleanup.');
  const response = await fetch(`http://${authHost}/emulator/v1/projects/demo-qlch-e2e/accounts`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error(`Failed to clear Auth Emulator users: ${response.status} ${response.statusText}.`);
  }
}

export async function cleanupE2EData(onProgress?: CleanupProgress): Promise<void> {
  await onProgress?.('read-manifest');
  const manifest = await readManifest();
  const { db, rtdb } = getE2EHarness();

  await deleteTaggedDocuments(manifest.runId, onProgress);

  // Explicit paths may include structured IDs generated by the server. Refuse
  // to delete them unless the route marked them as belonging to this exact run.
  for (const documentPath of manifest.dynamicDocumentPaths) {
    await onProgress?.('dynamic-documents');
    const ref = db.doc(documentPath);
    const snapshot = await ref.get();
    if (!snapshot.exists) continue;
    if (snapshot.data()?.e2eRunId !== manifest.runId) {
      throw new Error(`Refusing to delete unowned E2E document ${documentPath}.`);
    }
    await ref.delete();
  }

  for (const documentPath of manifest.staticDocumentPaths) {
    await onProgress?.('static-documents');
    const ref = db.doc(documentPath);
    const snapshot = await ref.get();
    if (!snapshot.exists) continue;
    if (snapshot.data()?.e2eRunId !== manifest.runId) {
      throw new Error(`Refusing to delete non-E2E fixture ${documentPath}.`);
    }
    await ref.delete();
  }

  await onProgress?.('active-shift');
  const activeShiftRef = db.doc('system_counters/active_cashier_shift');
  const activeShift = await activeShiftRef.get();
  if (activeShift.data()?.e2eRunId === manifest.runId) await activeShiftRef.delete();

  for (const uid of manifest.userUids) {
    await onProgress?.('rtdb-grants');
    await rtdb.ref(`admin_roles/${uid}`).remove();
  }

  await onProgress?.('rtdb-chat-fixtures');
  await rtdb.ref(`chats/${getScopedId('revocation-room', manifest.runId)}`).remove();

  await onProgress?.('auth-users');
  await clearAuthEmulatorUsers();
}

if (process.argv[1]?.replace(/\\/g, '/').endsWith('/cleanup.ts')) {
  cleanupE2EData().catch(error => { console.error(error); process.exitCode = 1; });
}
