import { readManifest } from './manifest';
import { getE2EHarness } from './harness';

const TAGGED_COLLECTIONS = [
  'orders',
  'repairs',
  'inventory_logs',
  'inventory_lots',
  'customer_ledger',
  'customer_transactions',
  'operation_requests',
  'cashier_shifts',
  'cashier_shift_movements',
  'commissions',
];

async function deleteTaggedDocuments(runId: string) {
  const { db } = getE2EHarness();
  for (const collection of TAGGED_COLLECTIONS) {
    const snapshot = await db.collection(collection).where('e2eRunId', '==', runId).get();
    const batch = db.batch();
    snapshot.docs.forEach(document => batch.delete(document.ref));
    if (!snapshot.empty) await batch.commit();
  }
}

export async function cleanupE2EData(): Promise<void> {
  const manifest = await readManifest();
  const { auth, db, rtdb } = getE2EHarness();

  await deleteTaggedDocuments(manifest.runId);

  // Explicit paths may include structured IDs generated by the server. Refuse
  // to delete them unless the route marked them as belonging to this exact run.
  for (const documentPath of manifest.dynamicDocumentPaths) {
    const ref = db.doc(documentPath);
    const snapshot = await ref.get();
    if (!snapshot.exists) continue;
    if (snapshot.data()?.e2eRunId !== manifest.runId) {
      throw new Error(`Refusing to delete unowned E2E document ${documentPath}.`);
    }
    await ref.delete();
  }

  for (const documentPath of manifest.staticDocumentPaths) {
    const ref = db.doc(documentPath);
    const snapshot = await ref.get();
    if (!snapshot.exists) continue;
    if (snapshot.data()?.e2eRunId !== manifest.runId) {
      throw new Error(`Refusing to delete non-E2E fixture ${documentPath}.`);
    }
    await ref.delete();
  }

  const activeShiftRef = db.doc('system_counters/active_cashier_shift');
  const activeShift = await activeShiftRef.get();
  if (activeShift.data()?.e2eRunId === manifest.runId) await activeShiftRef.delete();

  for (const uid of manifest.userUids) {
    await rtdb.ref(`admin_roles/${uid}`).remove();
    try { await auth.deleteUser(uid); } catch (error: unknown) {
      if (!(typeof error === 'object' && error && (error as { code?: string }).code === 'auth/user-not-found')) throw error;
    }
  }
}

if (process.argv[1]?.replace(/\\/g, '/').endsWith('/cleanup.ts')) {
  cleanupE2EData().catch(error => { console.error(error); process.exitCode = 1; });
}
