export type ExcelImportTemplateMode = 'product' | 'accessory' | 'part' | 'service' | 'customer' | 'supplier' | 'order' | 'repair';

export const EXCEL_IMPORT_PRIMARY_EXAMPLE_ROWS: Record<ExcelImportTemplateMode, string[]> = {
    product: ['iPhone 15 Pro Max 256GB', '', 'Apple', 'Điện thoại > iPhone > iPhone 15 Series', '29000000', '28500000', '27000000', 'NCC VN/A', '10', 'new', '12', 'Hàng chính hãng VN/A nguyên seal', 'https://example.com/iphone-15.jpg', 'https://example.com/iphone-15-2.jpg; https://example.com/iphone-15-3.jpg', 'Màn hình:6.7 inch; RAM:8GB; Bộ nhớ:256GB', 'iphone-15-pro-max', 'Titan tự nhiên', '256GB', 'yes', ''],
    accessory: ['Cáp sạc USB-C 60W chính hãng', '', 'Apple', 'Phụ kiện > Cáp sạc', '450000', '390000', '250000', 'NCC Phụ kiện', '30', 'new', '6', 'Cáp sạc nhanh USB-C 60W', 'https://example.com/cap-sac.jpg', '', 'Công suất:60W; Chuẩn:USB-C', ''],
    part: ['Màn hình iPhone 13 Pro Max Zin', '', 'Linh kiện Điện thoại > Màn hình', '1800000', '2500005', 'NCC Linh kiện', '5', 'Zin', 'Màn hình', 'iPhone 13 Pro Max', '6', 'Màn zin bóc máy, ép kính sẵn', 'https://example.com/man-iphone-13pm.jpg', ''],
    service: ['Thay pin iPhone 15 Pro Max', 'iPhone 15 Pro Max', 'Dịch vụ phổ biến > Thay Pin', '1500000', '1450000', '6 tháng', '30 phút', 'Pin dung lượng cao, bảo hành rõ ràng', 'https://example.com/thay-pin.jpg', 'https://example.com/thay-pin-2.jpg; https://example.com/thay-pin-3.jpg', 'Thay pin iPhone 15 Pro Max chính hãng, lấy liền tại cửa hàng.', 'pin, iphone, thay pin', ''],
    customer: ['KH-CU-0001', 'Nguyễn Văn A', '0912345678', '', '', 'SĐT', 'Khách lẻ', 'anguyen@example.com', '123 Đường Láng, Hà Nội', 'Thân thiết, Vip', '15000000', '5', '2', '0', 'Khách hay mua online'],
    supplier: ['NCC-CU-0001', 'Công ty Linh Kiện Hà Nội', '0243123456', '', '', 'SĐT', 'Anh Bình', 'contact@lkboard.vn', '789 Đường Láng, Hà Nội', 'Công ty cổ phần Linh Kiện Hà Nội', 'Màn hình', '0102030405', '123456789', 'Vietcombank', '30', 'Nguyễn Văn C', 'Linh kiện chính, Uy tín', '5000000', 'Công nợ còn sót lại từ hệ thống cũ; không import phiếu nhập hàng lịch sử'],
    order: ['HD-CU-0001', 'KH-CU-0001', 'Nguyễn Văn A', '0912345678', '', '', 'anguyen@example.com', '123 Đường Láng, Hà Nội', 'iPhone 13 Pro Max 256GB', '1', '14500000', '359999999999999', '12', '2025-08-01', '2026-08-01', '14500000', '0', '14500000', 'Completed', 'paid', 'COD', '2025-08-01', '2025-08-01', 'Đơn hàng chuyển từ hệ thống cũ'],
    repair: ['SC-CU-0001', 'KH-CU-0002', 'Trần Văn B', '0987654321', '', '', 'iPhone 14 Pro Max', '359888888888888', '123456', 'Tím', 'Thay pin; Vệ sinh máy', 'Pin iPhone 14 Pro Max|1|650000|6|2026-02-20', '650000', '200000', '0', '0', '0', '850000', 'paid', 'done', 'KTV Minh', '2025-08-20', '2025-08-21', '2025-08-21', '6', '2026-02-20', 'Máy hoạt động ổn định', 'Phiếu sửa chuyển từ hệ thống cũ'],
};

export const EXCEL_IMPORT_ADDITIONAL_EXAMPLE_ROWS: Record<ExcelImportTemplateMode, Record<string, string>> = {
    product: {
        'ten sp': 'Samsung Galaxy S25 Ultra 512GB',
        'ma hang': '',
        'thuong hieu': 'Samsung',
        'danh muc': 'Điện thoại > Samsung > Galaxy S Series',
        'gia goc': '31990000',
        'gia km': '29990000',
        'gia von': '28000000',
        ncc: 'NCC Samsung',
        'ton kho': '5',
        'tinh trang': 'new',
        'bao hanh thang': '12',
        'mo ta': 'Máy mới fullbox, bảo hành chính hãng.',
        'anh chinh': 'M:\\anh\\s25-ultra-front.png',
        'anh phu': 'M:\\anh\\s25-ultra-back.png; https://example.com/s25-side.webp',
        'thong so': 'Màn hình:6.8 inch; RAM:12GB; Bộ nhớ:512GB',
        'series id': 'galaxy-s25-ultra',
        'mau sac': 'Titan đen',
        'dung luong': '512GB',
        'flash sale': 'yes',
        video: 'https://www.youtube.com/watch?v=example',
    },
    accessory: {
        'ten phu kien': 'Ốp lưng chống sốc iPhone 15 Pro Max',
        'ma hang': '',
        'thuong hieu': 'UAG',
        'danh muc': 'Phụ kiện > Ốp lưng',
        'gia goc': '650000',
        'gia km': '590000',
        'gia von': '380000',
        ncc: 'NCC Phụ kiện',
        'ton kho': '20',
        'tinh trang': 'new',
        'bao hanh thang': '3',
        'mo ta': 'Ốp chống sốc, bảo vệ camera.',
        'anh chinh': 'op-lung-iphone-15pm.png',
        'anh phu': 'op-lung-iphone-15pm-2.png; op-lung-iphone-15pm-3.png',
        'thong so': 'Chất liệu:TPU; Màu:Đen',
        video: '',
    },
    part: {
        'ten linh kien': 'Pin iPhone 13 Pro Max Pisen',
        'ma hang': '',
        'danh muc': 'Linh kiện Điện thoại > Pin',
        'gia von': '420000',
        'gia ban': '650000',
        ncc: 'NCC Linh kiện',
        'ton kho': '8',
        'chat luong': 'Loại 1',
        'loai linh kien': 'Pin',
        'dong may tuong thich': 'iPhone 13 Pro Max',
        'bao hanh thang': '6',
        'mo ta': 'Pin dung lượng chuẩn, bảo hành 6 tháng.',
        'anh chinh': 'M:\\linh-kien\\pin-iphone-13pm.png',
        'anh phu': '',
    },
    service: {
        'ten dv': 'Ép kính iPhone 14 Pro Max',
        'dong may': 'iPhone 14 Pro Max',
        'danh muc': 'Dịch vụ phổ biến > Ép Kính',
        'gia goc': '900000',
        'gia km': '850000',
        'bao hanh': '30 ngày',
        'thoi gian sua': '2 giờ',
        'mo ta': 'Ép kính lấy liền, giữ màn zin nếu đủ điều kiện.',
        'anh chinh': 'ep-kinh-iphone-14pm.png',
        'anh phu': 'ep-kinh-iphone-14pm-2.png; https://example.com/ep-kinh-demo.webp',
        'seo description': 'Ép kính iPhone 14 Pro Max lấy liền, bảo hành rõ ràng tại cửa hàng.',
        tags: 'ep kinh, iphone, sua chua',
        video: 'https://www.youtube.com/watch?v=example',
    },
    customer: {
        'ma kh': 'KH-ZALO-LAN',
        'ten kh': 'Công ty TNHH MTV B',
        'sdt': '',
        zalo: 'Zalo chị Lan công ty B',
        facebook: 'facebook.com/congtyb',
        'kenh lien he chinh': 'Zalo',
        'loai kh': 'Khách sỉ',
        email: 'contact@companyb.com',
        'dia chi': '456 Lê Lợi, TP. HCM',
        tags: 'Khách sỉ, Linh kiện',
        'chi tieu': '50000000',
        'don hang': '12',
        'sua chua': '0',
        'cong no': '-1500000',
        'ghi chu': 'Đang dư cọc',
    },
    supplier: {
        'ma ncc': 'NCC-PISEN-CU',
        'ten ncc': 'Nhà phân phối Pisen Việt Nam',
        'sdt': '',
        zalo: 'Zalo chị Hoa Pisen',
        facebook: '',
        'kenh lien he chinh': 'Zalo',
        'nguoi lien he': 'Chị Hoa',
        email: 'sales@pisenvietnam.vn',
        'dia chi': '101 Nguyễn Huệ, TP. HCM',
        'cong ty': 'Công ty TNHH Pisen Việt Nam',
        'phan loai': 'Pin',
        'ma so thue': '0304050607',
        'so tai khoan': '987654321',
        'ngan hang': 'Techcombank',
        'han thanh toan': '15',
        'phu trách': 'Trần Văn D',
        tags: 'Chính hãng, Pin Pisen',
        'cong no': '-2000000',
        'ghi chu': 'Công nợ còn sót lại từ hệ thống cũ; không import phiếu nhập hàng lịch sử',
    },
    order: {
        'ma don': 'HD-CU-0002',
        'ma kh': 'KH-ZALO-LAN',
        'ten kh': 'Lê Thị C',
        sdt: '',
        zalo: 'Zalo chị C',
        facebook: '',
        email: 'lethi@example.com',
        'dia chi': '12 Nguyễn Trãi, Hà Nội',
        'san pham': 'Ốp lưng chống sốc iPhone 15 Pro Max',
        'so luong': '2',
        'don gia': '250000',
        'imei/serial': '',
        'bao hanh thang': '3',
        'ngay bat dau bh': '2025-09-15',
        'ngay het bh': '2025-12-15',
        'tam tinh': '500000',
        'giam gia': '50000',
        'tong tien': '450000',
        'trang thai': 'Completed',
        'thanh toan': 'paid',
        'phuong thuc': 'COD',
        'ngay tao': '2025-09-15',
        'ngay hoan thanh': '2025-09-15',
        'ghi chu': 'Đơn phụ kiện cũ',
    },
    repair: {
        'ma phieu': 'SC-CU-0002',
        'ma kh': 'KH-FB-D',
        'ten kh': 'Phạm Văn D',
        sdt: '',
        zalo: '',
        facebook: 'facebook.com/phamvand',
        'thiet bi': 'Samsung S23 Ultra',
        'imei/serial': '358777777777777',
        'mat khau': '1->2->3->6->9',
        'mau may': 'Đen',
        'loi/benh': 'Không sạc; Thay chân sạc',
        'linh kien': 'Chân sạc S23 Ultra|1|450000|3|2025-12-30',
        'tien linh kien': '450000',
        'phi sua chua': '250000',
        'phi phat sinh': '0',
        'giam gia': '0',
        'da coc': '200000',
        'tong tien': '700000',
        'thanh toan': 'debt',
        'trang thai': 'done',
        ktv: 'KTV Hùng',
        'ngay nhan': '2025-09-30',
        'ngay hen tra': '2025-10-01',
        'ngay hoan thanh': '2025-10-01',
        'bao hanh dich vu thang': '3',
        'ngay het bh dich vu': '2025-12-30',
        'ghi chu ky thuat': 'Đã thay chân sạc, test dòng ổn định',
        'ghi chu': 'Còn nợ 500000',
    },
};
