export type ExcelImportTemplateMode = 'product' | 'accessory' | 'part' | 'service';

export const EXCEL_IMPORT_PRIMARY_EXAMPLE_ROWS: Record<ExcelImportTemplateMode, string[]> = {
    product: ['iPhone 15 Pro Max 256GB', '', 'Apple', 'Điện thoại > iPhone > iPhone 15 Series', '29000000', '28500000', '27000000', 'NCC VN/A', '10', 'new', '12', 'Hàng chính hãng VN/A nguyên seal', 'https://example.com/iphone-15.jpg', 'https://example.com/iphone-15-2.jpg; https://example.com/iphone-15-3.jpg', 'Màn hình:6.7 inch; RAM:8GB; Bộ nhớ:256GB', 'iphone-15-pro-max', 'Titan tự nhiên', '256GB', 'yes', ''],
    accessory: ['Cáp sạc USB-C 60W chính hãng', '', 'Apple', 'Phụ kiện > Cáp sạc', '450000', '390000', '250000', 'NCC Phụ kiện', '30', 'new', '6', 'Cáp sạc nhanh USB-C 60W', 'https://example.com/cap-sac.jpg', '', 'Công suất:60W; Chuẩn:USB-C', ''],
    part: ['Màn hình iPhone 13 Pro Max Zin', '', 'Linh kiện Điện thoại > Màn hình', '1800000', '2500000', 'NCC Linh kiện', '5', 'Zin', 'Màn hình', 'iPhone 13 Pro Max', '6', 'Màn zin bóc máy, ép kính sẵn', 'https://example.com/man-iphone-13pm.jpg', ''],
    service: ['Thay pin iPhone 15 Pro Max', 'iPhone 15 Pro Max', 'Dịch vụ phổ biến > Thay Pin', '1500000', '1450000', '6 tháng', '30 phút', 'Pin dung lượng cao, bảo hành rõ ràng', 'https://example.com/thay-pin.jpg', 'https://example.com/thay-pin-2.jpg; https://example.com/thay-pin-3.jpg', 'Thay pin iPhone 15 Pro Max chính hãng, lấy liền tại cửa hàng.', 'pin, iphone, thay pin', ''],
};

export const EXCEL_IMPORT_ADDITIONAL_EXAMPLE_ROWS: Record<ExcelImportTemplateMode, Record<string, string>> = {
    product: {
        'ten sp': 'Samsung Galaxy S25 Ultra 512GB',
        'ma hang': '',
        'thuong hieu': 'Samsung',
        'danh muc': 'Điện thoại > Samsung > Galaxy S Series',
        'gia goc': '31990000',
        'gia km': '29990000',
        'gia von': '28000000',
        ncc: 'NCC Samsung',
        'ton kho': '5',
        'tinh trang': 'new',
        'bao hanh thang': '12',
        'mo ta': 'Máy mới fullbox, bảo hành chính hãng.',
        'anh chinh': 'M:\\anh\\s25-ultra-front.png',
        'anh phu': 'M:\\anh\\s25-ultra-back.png; https://example.com/s25-side.webp',
        'thong so': 'Màn hình:6.8 inch; RAM:12GB; Bộ nhớ:512GB',
        'series id': 'galaxy-s25-ultra',
        'mau sac': 'Titan đen',
        'dung luong': '512GB',
        'flash sale': 'yes',
        video: 'https://www.youtube.com/watch?v=example',
    },
    accessory: {
        'ten phu kien': 'Ốp lưng chống sốc iPhone 15 Pro Max',
        'ma hang': '',
        'thuong hieu': 'UAG',
        'danh muc': 'Phụ kiện > Ốp lưng',
        'gia goc': '650000',
        'gia km': '590000',
        'gia von': '380000',
        ncc: 'NCC Phụ kiện',
        'ton kho': '20',
        'tinh trang': 'new',
        'bao hanh thang': '3',
        'mo ta': 'Ốp chống sốc, bảo vệ camera.',
        'anh chinh': 'op-lung-iphone-15pm.png',
        'anh phu': 'op-lung-iphone-15pm-2.png; op-lung-iphone-15pm-3.png',
        'thong so': 'Chất liệu:TPU; Màu:Đen',
        video: '',
    },
    part: {
        'ten linh kien': 'Pin iPhone 13 Pro Max Pisen',
        'ma hang': '',
        'danh muc': 'Linh kiện Điện thoại > Pin',
        'gia von': '420000',
        'gia ban': '650000',
        ncc: 'NCC Linh kiện',
        'ton kho': '8',
        'chat luong': 'Loại 1',
        'loai linh kien': 'Pin',
        'dong may tuong thich': 'iPhone 13 Pro Max',
        'bao hanh thang': '6',
        'mo ta': 'Pin dung lượng chuẩn, bảo hành 6 tháng.',
        'anh chinh': 'M:\\linh-kien\\pin-iphone-13pm.png',
        'anh phu': '',
    },
    service: {
        'ten dv': 'Ép kính iPhone 14 Pro Max',
        'dong may': 'iPhone 14 Pro Max',
        'danh muc': 'Dịch vụ phổ biến > Ép Kính',
        'gia goc': '900000',
        'gia km': '850000',
        'bao hanh': '30 ngày',
        'thoi gian sua': '2 giờ',
        'mo ta': 'Ép kính lấy liền, giữ màn zin nếu đủ điều kiện.',
        'anh chinh': 'ep-kinh-iphone-14pm.png',
        'anh phu': 'ep-kinh-iphone-14pm-2.png; https://example.com/ep-kinh-demo.webp',
        'seo description': 'Ép kính iPhone 14 Pro Max lấy liền, bảo hành rõ ràng tại cửa hàng.',
        tags: 'ep kinh, iphone, sua chua',
        video: 'https://www.youtube.com/watch?v=example',
    },
};
